// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: internal/grpc/proto/user.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Activated     bool                   `protobuf:"varint,6,opt,name=activated,proto3" json:"activated,omitempty"`
	Verified      bool                   `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Rating        float64                `protobuf:"fixed64,10,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_grpc_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *User) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *User) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_grpc_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_user_proto_rawDescGZIP(), []int{1}
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID string format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_internal_grpc_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserIdList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // UUID string format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdList) Reset() {
	*x = UserIdList{}
	mi := &file_internal_grpc_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdList) ProtoMessage() {}

func (x *UserIdList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdList.ProtoReflect.Descriptor instead.
func (*UserIdList) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserIdList) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UserResponseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponseList) Reset() {
	*x = UserResponseList{}
	mi := &file_internal_grpc_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponseList) ProtoMessage() {}

func (x *UserResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponseList.ProtoReflect.Descriptor instead.
func (*UserResponseList) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserResponseList) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_internal_grpc_proto_user_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/grpc/proto/user.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x02\n" +
	"\x04User\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x1c\n" +
	"\tactivated\x18\x06 \x01(\bR\tactivated\x12\x1a\n" +
	"\bverified\x18\a \x01(\bR\bverified\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tlast_seen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x01R\x06rating\"\a\n" +
	"\x05Empty\"!\n" +
	"\x06UserId\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"'\n" +
	"\n" +
	"UserIdList\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"4\n" +
	"\x10UserResponseList\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users2\xa7\x01\n" +
	"\vUserService\x12%\n" +
	"\aGetUser\x12\f.user.UserId\x1a\n" +
	".user.User\"\x00\x12>\n" +
	"\x10GetMultipleUsers\x12\x10.user.UserIdList\x1a\x16.user.UserResponseList\"\x00\x121\n" +
	"\bGetUsers\x12\v.user.Empty\x1a\x16.user.UserResponseList\"\x00B\x0fZ\rinternal/grpcb\x06proto3"

var (
	file_internal_grpc_proto_user_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_user_proto_rawDescData []byte
)

func file_internal_grpc_proto_user_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_user_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_user_proto_rawDesc), len(file_internal_grpc_proto_user_proto_rawDesc)))
	})
	return file_internal_grpc_proto_user_proto_rawDescData
}

var file_internal_grpc_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_grpc_proto_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: user.User
	(*Empty)(nil),                 // 1: user.Empty
	(*UserId)(nil),                // 2: user.UserId
	(*UserIdList)(nil),            // 3: user.UserIdList
	(*UserResponseList)(nil),      // 4: user.UserResponseList
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_internal_grpc_proto_user_proto_depIdxs = []int32{
	5, // 0: user.User.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: user.User.last_seen:type_name -> google.protobuf.Timestamp
	0, // 2: user.UserResponseList.users:type_name -> user.User
	2, // 3: user.UserService.GetUser:input_type -> user.UserId
	3, // 4: user.UserService.GetMultipleUsers:input_type -> user.UserIdList
	1, // 5: user.UserService.GetUsers:input_type -> user.Empty
	0, // 6: user.UserService.GetUser:output_type -> user.User
	4, // 7: user.UserService.GetMultipleUsers:output_type -> user.UserResponseList
	4, // 8: user.UserService.GetUsers:output_type -> user.UserResponseList
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_user_proto_init() }
func file_internal_grpc_proto_user_proto_init() {
	if File_internal_grpc_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_user_proto_rawDesc), len(file_internal_grpc_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_user_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_user_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_user_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_user_proto = out.File
	file_internal_grpc_proto_user_proto_goTypes = nil
	file_internal_grpc_proto_user_proto_depIdxs = nil
}
